Add HTTP2 support (#87)
* Add HTTP2 support

Signed-off-by: Darshan Sen <raisinten@gmail.com>

* Add TODO

Signed-off-by: Darshan Sen <raisinten@gmail.com>

* Set `10.15` as the `MACOSX_DEPLOYMENT_TARGET` value for the binding

Fixes: https://app.circleci.com/pipelines/github/postmanlabs/wormhole/213/workflows/a8405095-0eb4-44e3-aeeb-89e0b4a75853/jobs/644?invite=true#step-106-655
```sh
../relocatable_libwormhole_x86_64/include/request.h:28:34: error: 'path' is unavailable: introduced in macOS 10.15
  std::optional<std::filesystem::path> ca_bundle() const { return ca_bundle_;
```

The minimum macOS deployment target was previously set to `10.13` by
default on CI as Node.js v16.15.1 is being used there currently. See the
`-mmacosx-version-min=10.13` option in
https://app.circleci.com/pipelines/github/postmanlabs/wormhole/213/workflows/a8405095-0eb4-44e3-aeeb-89e0b4a75853/jobs/644?invite=true#step-106-653.
However, it needs to be set to `10.15` in order to use
`std::filesystem::path`.

Signed-off-by: Darshan Sen <raisinten@gmail.com>

---------

Signed-off-by: Darshan Sen <raisinten@gmail.com>