Turn the Node.js addon into an async and non-blocking API (#75)
* Turn the Node.js addon into an async and non-blocking API

Signed-off-by: Darshan Sen <raisinten@gmail.com>

* Build Node.js C++ addon with C++17

Since `std::optional` is only available in C++17 or higher, this option
is required.

Fixes: https://app.circleci.com/pipelines/github/postmanlabs/wormhole/179/workflows/67a04a04-0e72-4ec3-b3a0-f876eb03f127/jobs/353?invite=true#step-106-46
```sh
../binding/binding.cc:31:8: error: no template named 'optional' in namespace 'std'
  std::optional<wormhole::Response> response_;
  ~~~~~^
```

Signed-off-by: Darshan Sen <raisinten@gmail.com>

---------

Signed-off-by: Darshan Sen <raisinten@gmail.com>