Update curl to 8.1.2 (#124)
* Update curl to 8.1.2

Refs: https://github.com/curl/curl/releases/tag/curl-8_1_2
Signed-off-by: Darshan Sen <raisinten@gmail.com>

* Update ngtcp2 to v0.16.0

To fix this curl build error -
https://app.circleci.com/pipelines/github/postmanlabs/wormhole/394/workflows/651931c4-e452-4340-aefa-7384817b498e/jobs/2165?invite=true#step-105-5136
```cc
vquic/curl_ngtcp2.c:143:3: error: unknown type name 'ngtcp2_ccerr'
  ngtcp2_ccerr last_error;
  ^
```

The `ngtcp2_ccerr` type was probably introduced later on.

Refs: https://github.com/ngtcp2/ngtcp2/releases/tag/v0.16.0
Signed-off-by: Darshan Sen <raisinten@gmail.com>

* Downgrade ngtcp2 to v0.15.0

In https://app.circleci.com/pipelines/github/postmanlabs/wormhole/395/workflows/7d346fbc-7696-49a4-b8fa-be80e3cfa360/jobs/2173?invite=true#step-105-5137,
we were facing the same issue as the one reported in
https://github.com/curl/curl/issues/11190, the fix for which
(https://github.com/curl/curl/pull/11184) won't land until ngtcp2
releases another version. No need to wait for that, so let's use the
previous ngtcp2 version.

Refs: https://github.com/ngtcp2/ngtcp2/releases/tag/v0.15.0
Signed-off-by: Darshan Sen <raisinten@gmail.com>

* Rename libngtcp2.10.dylib to libngtcp2.12.dylib

Fixes https://app.circleci.com/pipelines/github/postmanlabs/wormhole/396/workflows/4b918093-cbd2-4f0b-9c1f-40c9be33cd98/jobs/2182?invite=true#step-106-34
```sh
dyld[3292]: Library not loaded: '/Users/distiller/project/curl_build/vendor_install/lib/libngtcp2.12.dylib'
  Referenced from: '/Users/distiller/project/relocatable_libcurl_arm64/lib/libcurl.dylib'
  Reason: tried: '/Users/distiller/project/curl_build/vendor_install/lib/libngtcp2.12.dylib' (no such file), '/usr/local/lib/libngtcp2.12.dylib' (no such file), '/usr/lib/libngtcp2.12.dylib' (no such file)
```

Signed-off-by: Darshan Sen <raisinten@gmail.com>

---------

Signed-off-by: Darshan Sen <raisinten@gmail.com>